### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by wind91725** [jiangtaojy/mlm_bert_traning#3]
你好，请问能否提供预训练模型，且我有几个问题：
1、请问你的预训练数据是多少？
2、这个模型是否是个通用模型，在特定场景下也需要如图bert一样去调优?
3、这个方法在asr文本纠错中的效果如何？
 本人刚开始做asr文本纠错，不知道能否给点建议啥的 O(∩_∩)O哈哈~ 谢谢大佬

**Comment by jiangtaojy** [comment]
@wind91725 你好，可以提供预训练模型，一一回复:
1.  1000w，可以小一点也没关系
2.  我的训练数据是针对特定任务的，因此你可能需要在自己的训练数据上进行调整
3.  在我的尝试中效果很好
建议：可以应用到asr纠错，asr部分可以考虑只输出拼音

**Comment by wind91725** [comment]
好的 谢谢大佬 麻烦提供一下 模型下载链接呀

**Comment by wind91725** [comment]
你好 能否给个模型下载链接呀

**Comment by jiangtaojy** [comment]
请留下邮箱

**Comment by wind91725** [comment]
WangC_lucky@126.com

**Comment by jiangtaojy** [comment]
Sent

**Comment by aidatatech** [comment]
我这边有个疑问：
如果ASR识别结果直接是文字，是否要先转换为拼音，然后再全部进行识别一遍？如果只想纠正里面的一些热词，可以吗？

挺好的工作，顺便问下能发下模型我研究下吗guanxs_ai@126.com，多谢。

**Comment by jiangtaojy** [comment]
@aidatatech 是的，关于纠正哪一部分在于你的训练数据是如何构造的。模型已发。

**Comment by JunnYu** [comment]
@jiangtaojy  同求训练好的模型y45190321@mail.ecust.edu.cn，谢谢。

**Comment by jiangtaojy** [comment]
@JunnYu Sent
