### ISSUE TITLE
想要一下你的预训练模型

### ISSUE THREAD

**Issue by liubin3702** [jiangtaojy/mlm_bert_traning#4]
自己预训练的话 是需要用utils.py的模糊音算法来构造一批数据是吧，构造数据错误特征要自己从声学模型中找，构造后再投入训练。

**Comment by jiangtaojy** [comment]
是的，请留下邮箱

**Comment by liubin3702** [comment]
谢谢，这是我的邮箱 18851995518@163.com  还想请问一下 构造模糊音算法主要是 replace_sim 和replace_sim2 是吧，可以在直接给正确拼音训练的过程中就添加错误吗，不用单独把构造数据保存下来。最后您这边在专有领域文本wer能到多少？

**Comment by jiangtaojy** [comment]
Sent，代码中就是直接添加的，另外wer值主要依赖于声学模型的输出

**Comment by liubin3702** [comment]
OK，我在看看代码

**Comment by liubin3702** [comment]
训练数据的拼音和汉字不等长就会报错？ 只能构造替代错误吗

**Comment by liubin3702** [comment]
你好，打扰了，您的代码里目前对于输入和标签不等长是有报错的，这个您知道吗？对于删除或者插入错误是怎么解决的呢？










在 2020-12-24 15:39:22，"jiangtao" <notifications@github.com> 写道：

Sent，代码中就是直接添加的，另外wer值主要依赖于声学模型的输出

**Comment by jiangtaojy** [comment]
本模型只具有纠错功能，针对不等长可以尝试生成式模型
